#!/usr/bin/env bash
# A script that displays "Best Schoool" and "Hi" on the 9th line

i=0

while [ $i -le 9 ]
do
    if [ $i -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((i++))
done
