#!/usr/bin/env bash
#script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

myfiles=$(ls)

for i in $myfiles; do
    echo "$i" | cut -d '-' -f2
done
